# Generated by Django 3.2.8 on 2021-10-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ratings_count', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, to='api.Author')),
                ('categories', models.ManyToManyField(blank=True, to='api.Category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
