# Generated by Django 3.2.8 on 2021-10-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256)),
                ('published_date', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
