# Generated by Django 3.2.8 on 2021-10-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publishedDate', models.DateField()),
                ('averageRating', models.FloatField(default=0)),
                ('ratingsCount', models.IntegerField(default=0)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, to='api.Author')),
                ('categories', models.ManyToManyField(blank=True, to='api.Category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
