# Generated by Django 3.2.8 on 2021-10-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.TextField(),
        ),
    ]
