# Generated by Django 3.2.8 on 2021-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211028_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avaerage_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
    ]
